/**
 * POST /api/outreach/bulk-generate
 *
 * Generate and persist outreach messages for a list of entity IDs.
 * Uses the same single-Opus generation pipeline as the individual generate-message endpoint.
 * Messages are written to Kissinger as meta fields (outreach_message, etc.)
 * and returned in the response.
 *
 * Request body (JSON):
 * {
 *   entityIds: string[],    // Kissinger entity IDs to generate for
 *   assignee?: "Ben" | "Jake" | "Drew"  // override — otherwise auto-assigned by sector
 * }
 *
 * Response:
 * {
 *   generated: number,
 *   failed: number,
 *   results: Array<{ entityId: string, status: "ok" | "failed", message?: string, source?: "claude" | "template", error?: string }>
 * }
 */

import { NextRequest, NextResponse } from "next/server";
import { fetchProspectContacts, mergeEntityMeta } from "@/lib/kissinger";
import { distributeContacts, type TeamMember } from "@/lib/outreach";
import { generateOpusMessage } from "@/lib/outreach-generate";

const MAX_ENTITY_IDS = 200;

interface BulkResult {
  entityId: string;
  status: "ok" | "failed";
  message?: string;
  /** Whether the message was generated by Claude (Opus) or the template engine. */
  source?: "claude" | "template";
  error?: string;
}

export async function POST(request: NextRequest) {
  let body: { entityIds?: string[]; assignee?: TeamMember };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { entityIds, assignee: assigneeOverride } = body;

  if (!Array.isArray(entityIds) || entityIds.length === 0) {
    return NextResponse.json(
      { error: "entityIds must be a non-empty array of strings" },
      { status: 400 }
    );
  }

  if (entityIds.length > MAX_ENTITY_IDS) {
    return NextResponse.json(
      { error: `Maximum ${MAX_ENTITY_IDS} entity IDs per request` },
      { status: 400 }
    );
  }

  if (
    assigneeOverride !== undefined &&
    !["Ben", "Jake", "Drew"].includes(assigneeOverride)
  ) {
    return NextResponse.json(
      { error: "assignee must be one of: Ben, Jake, Drew" },
      { status: 400 }
    );
  }

  const entityIdSet = new Set(entityIds);

  // Fetch all prospect contacts from Kissinger (includes notes, linkedinUrl, sector, etc.)
  const allContacts = await fetchProspectContacts();
  if (allContacts === null) {
    return NextResponse.json({ error: "Kissinger unreachable" }, { status: 503 });
  }

  // Filter to only the requested IDs
  const targeted = allContacts.filter((c) => entityIdSet.has(c.id));

  if (targeted.length === 0) {
    return NextResponse.json({
      generated: 0,
      failed: 0,
      results: [],
      note: "No matching prospect-contact entities found for provided IDs",
    });
  }

  // Map to ProspectContact shape — pass ALL available fields including notes and linkedinUrl
  const contacts = targeted.map((raw) => ({
    id: raw.id,
    name: raw.name,
    title: raw.title,
    company: raw.company,
    sector: raw.sector,
    fitTier: raw.fitTier,
    notes: raw.notes || undefined,
    outreachStage: raw.outreachStage,
    linkedinUrl: raw.linkedinUrl || undefined,
  }));

  // Distribute to determine assignees (unless overridden)
  const distributed = distributeContacts(contacts);

  // Process contacts sequentially to avoid overwhelming the API
  // (Opus calls are expensive — serial is safer for bulk)
  const results: BulkResult[] = [];

  for (const contact of contacts) {
    // Determine assignee: override → sector assignment
    let assignee: TeamMember;
    if (assigneeOverride) {
      assignee = assigneeOverride;
    } else {
      const bucket = (["Ben", "Jake", "Drew"] as TeamMember[]).find((m) =>
        distributed[m].some((t) => t.contact.id === contact.id)
      );
      assignee = bucket ?? "Drew";
    }

    try {
      // Use the shared Opus generation logic — identical to individual endpoint
      const result = await generateOpusMessage(contact, assignee);

      // Persist to Kissinger
      await mergeEntityMeta(contact.id, {
        outreach_message: result.message,
        outreach_message_generated_at: new Date().toISOString(),
        outreach_message_sender: assignee.toLowerCase(),
      });

      results.push({
        entityId: contact.id,
        status: "ok",
        message: result.message,
        source: result.source,
      });
    } catch (err) {
      results.push({
        entityId: contact.id,
        status: "failed",
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  const generated = results.filter((r) => r.status === "ok").length;
  const failed = results.filter((r) => r.status === "failed").length;

  return NextResponse.json({ generated, failed, results });
}
